# The URL where your blog is hosted
base_url = "https://omee-y.github.io/my-diary"

# Disable Sass compilation
compile_sass = false

# Build search index
build_search_index = true

[markdown]
# Enable syntax highlighting with Dracula theme
highlighting = "dracula"

[extra]